### ISSUE TITLE
Synthesizer audio stream

### ISSUE THREAD

**Issue by teotigraphix** [Tracktion/tracktion_engine#1]
Hi,

I have been looking at the source code and wasn't expecting a full answer just how exactly do you plugin into the audio stream with say a simple sine generator using a midi clip? e.g. like the `getNextAudioBlock()` in JUCE.

This seems like a good/quick tutorial for concepts.

**Comment by teotigraphix** [comment]
Ok, Figured this out for the time being.

Plugin has Plugin::prepareForNextBlock()

**Comment by drowaudio** [comment]
That's not quite the same thing, `prepareForNextBlock` is like a prefetch, you probably want `renderOver` or `renderAdding`.
However, if you're implementing a `Plugin`, that will get called automatically with `Plugin::applyToBuffer`

**Comment by teotigraphix** [comment]
Is there any gotchas or places in the code already that show how to implement a Plugin and register with the engine/project?

**Comment by drowaudio** [comment]
Maybe take a look at `CompressorPlugin` to see how that gets defined, registered with the model and then created when needed by the `PluginManager`?
