### ISSUE TITLE
Disabling MackieC4 while control surfaces are enabled

### ISSUE THREAD

**Issue by vassilisw** [Tracktion/tracktion_engine#109]
It seems that `tracktion_MackieC4.cpp` is still included when `TRACKTION_ENABLE_CONTROL_SURFACES` is enabled and `TRACKTION_ENABLE_CONTROL_SURFACE_MACKIEC4` is disabled.  
The compilation fails of course. I guess that this has been overlooked.  
The following changes fix the issue...

![image](https://user-images.githubusercontent.com/16954451/151039351-a9e09e80-260d-4b7c-bae4-bcd7ff90a1e1.png)

**Comment by FigBug** [comment]
Fixed in 15a615964f7a4f23ac50ad265152f10fe7931e55
