### ISSUE TITLE
playback: MidiOutputDevice tries to access MouseCursor even if it is a console project.

### ISSUE THREAD

**Issue by atsushieno** [Tracktion/tracktion_engine#11]
I am trying to create a very simple console tool that loads some Edit file. It is like PlaybackDemo, but is a JUCE ConsoleApplication project. At first few lines:

```
int main (int argc, char* argv[])
{
    juce::MessageManager::getInstance(); // not sure if I should need this, app crashes without it.

    std::unique_ptr<te::Edit> edit;
    te::Engine engine { ProjectInfo::projectName };
```

The app crashed as it tried to access to mouse cursor, which does not exist on a console application.

I'm kind of sure that it is unwanted. This makes it impossible to write console based tools for this tracktion engine.

Removing these lines (`showWaitCursor()` and `hideWaitCursor()` in this function, and `MidiInputDevice` on the same principle) fixes the issue.

https://github.com/Tracktion/tracktion_engine/blob/f1380028/modules/tracktion_engine/playback/devices/tracktion_MidiOutputDevice.cpp#L282

Reproduced on Ubuntu 18.04, tracktion_engine rev: 1463f85

**Comment by drowaudio** [comment]
Are you sure it actually crashes? Or is there just some assertion somewhere? If it's a crash, can you show me a stack trace?
Tracktion Engine needs the message loop to run as lots of internal workings are asynchronous and threaded.

Perhaps what you really need to do is run a UI app but simply quit when you've done your task?
Have a look at the Projucer in JUCE and `pluginval` here: https://github.com/Tracktion/pluginval for how to do this. They both have command-line modes.
