### ISSUE TITLE
Make more classes inherit from juce::ReferenceCountedObject

### ISSUE THREAD

**Issue by adamnemecek** [Tracktion/tracktion_engine#112]
Is there a good argument for why e.g. `te::MidiEvent` or `te::MidiEventHolder` should not inherit from `juce::ReferenceCountedObject`?

In my code I keep a reference to some of these pointers. Before I made `te::MidiEvent` inherit from `juce::ReferenceCountedObject`, I would get a lot of `dangling pointer` warnings after the program terminated. Once I made it inherit from `juce::ReferenceCountedObject`, the warnings went away. I'm not sure if this is the right way of solving this though.

**Comment by drowaudio** [comment]
I think this was discussed at length on discord and the conclusion was this isn't a good way to hold on to MIDI notes.
