### ISSUE TITLE
EqualizerPlugin.cpp lines 71->73 and 83->85 say 'High/Low-pass' when they should say 'High/Low-shelf'

### ISSUE THREAD

**Issue by jamierpond** [Tracktion/tracktion_engine#116]
Hey guys, I think there are some typos in the Equalizer plugin cpp file. I think they are minor ones, but it changes the meaning of the label quite a lot!

Currently:
```
addAutomatableParameter (hiFreq = new EQAutomatableParameter (*this, "High-pass freq", TRANS("High-shelf freq"), *this, { 
```

Should be:
```
addAutomatableParameter (hiFreq = new EQAutomatableParameter (*this, "High-**shelf** freq", TRANS("High-shelf freq"), *this, { 
```

**Comment by drowaudio** [comment]
Yeah maybe that would be a better name but it can't be changed now as that's the property the model references and is stored in the XML file. If we changed it, all existing sessions would break and it's not significant enough a change to add the the edit conversion pass (which would break minor version backwards compatibility which we rely on for testing).

**Comment by jamierpond** [comment]
Oh damn, I see! Sorry I didn't see this before the PR. That makes sense. Would be cool to find a solution for this at some point!
