### ISSUE TITLE
Add xmlns:base64='(something)' on the root element in `*.tracktionedit`

### ISSUE THREAD

**Issue by atsushieno** [Tracktion/tracktion_engine#12]
I'm trying to write some custom tool that makes custom manipulation on `*.tracktionedit` files (directly, I have some MIDI manipulation library to play with it) and tried to load it as XML. It is doable, but while it is technically a well-formed XML, it violates Namespaces in XML W3C specification ( https://www.w3.org/TR/xml-names/ ). The specification says, if an XML name is parsed as a namespace prefix and a local name, separate by ':', then the corresponding namespace prefix must be declared using a namespace delcration (`xmlns:foobar`).

The problematic point is `base64:layout` attribute in `FILTER` element. By using "base64" namespace prefix, there should be a namespace declaration with some URI. `*.tracktionedit` files don't contain that.

It is "technically" still well-formed XML, but it violates namespaces in XML specification, meaning that a lot of XML processors and libraries won't be able to handle it. I'm using .NET now and I had to use .NET 1.0 feature which is practically deprecated in .NET 2.0.

Solution: add `xmlns:base64='(some_url)'` to the top-level element (anywhere above `FILTER` attribute, but the root element would make most sense).

Benefit: those `*.tracktionedit` files can be then loaded by many general XML processors.

Giving XML namespace URI for some element or attribute (XML Infoset) is generally a breaking change, but since this `*.tracktionedit` XML was never a valid XML with namespaces, any XML parsers which treated these files must have ignored namespaces, it won't break any existing tooling, if any.

(This format being accepted by JUCE means that JUCE XML parser does not really care about XML namespaces, which brings me some concern about JUCE API, but anyways...)

**Comment by atsushieno** [comment]
I grepped around the sources but I couldn't find any place where the OSS part of the engine emits "base64" prefix for `layout` attribute. It is possible that it happens only on the product version of Waveform9.3.x (2 or 6, whichever when I created some song file with MIDI import feature). FilterGraph seems to be part of JUCE feature and XML serialization may be too. If that's the case it may not happen in the code in this repository anymore.

**Comment by drowaudio** [comment]
It gets prepended when you write a `juce::var` that is a `juce::MemoryBlock` to XML (via a `juce::ValueTree`).

If we added this to the top level node (i.e. the `EDIT` node), what would the URL have to be? Would this be ok: https://docs.juce.com/master/structBase64.html?

**Comment by atsushieno** [comment]
It would be OK, but now that it seems to be JUCE side of the problem, it is possible that JUCE developers (I'm not sure how much you guys and the JUCE team overlaps!) would give different namespace URI for that prefix later. It might be better to have some concensus with them.

As an application (XML processor) developer, I don't have any opinion on what the namespace URI should look like. My concern and point is only about the existence of xmlns :-)

**Comment by drowaudio** [comment]
Does it matter if the namespace URI changes? Or is different between different projects?
Surely the declaration is scoped to that particular document and is a hint for how that data should be interpreted?

I think linking to the docs for the base 64 conversion is probably the best we can do here?

**Comment by atsushieno** [comment]
Yes it matters. Once the namespace is determined, changing that later will break any code that was written for the former namespace. This is an example of how to query the XML attribute from a `FILTER` element:

```
var layout = filterElement.getAttributeNS ("layout", "https://docs.juce.com/master/structBase64.html");
```

If the namespace is changed to e.g. "urn:juce-datatypes-base64" it has to become like:

```
var layout = filterElement.getAttributeNS ("layout", "urn:juce-datatypes-base64");
```

On a side note, `*.tracktionedit` XML files can just give other "layout" attributes with the same content, in different namespace prefixes (or without prefix, meaning that it has the empty namespace).

If it were just you who will determine the namespace URI, then it is simple - you just don't change it. But in this case whether the namespace URI changes or not would depend on JUCE (they may give different namespace later), which could then bring mess later. **Right now** it is only a per-project matter and you can give an arbitrary namespace URI, but if the JUCE project determines the XML infoset semantics, you don't want to go differently.

**Comment by drowaudio** [comment]
I'm not really sure what the best solution is here then.
I'm hesitant to put anything in the code that _might_ change over time.
As this namespace is added by JUCE, it seems like perhaps it should live in the JUCE code so any XML that has namespace in has the same URI?

**Comment by drowaudio** [comment]
I'm going to close this now the issue has moved to JUCE. However, I still don't see how this breaks things in the future if the URI did change. What is the practical thing that would break if the URL changed from "https://docs.juce.com/master/structBase64.html" to a different URL that perhaps describes the actual encoding better?

**Comment by atsushieno** [comment]
Note that it is part of the arguments for attribute queries. It is like, if you change the top level element name from "EDIT" to "Edit" then any XML processor that queries "EDIT" will not find the root node. The same will happen to attributes in different namespace URI.
