### ISSUE TITLE
LevelMeasurer getNumActiveChannels always returns 1

### ISSUE THREAD

**Issue by hgroenenboom** [Tracktion/tracktion_engine#149]
While trying to use the LevelMeasurer::getNumActiveChannels() method, I noticed that the `numActiveChannels` field is never changed, so it is always set to 1.

**Comment by drowaudio** [comment]
Can I ask what the use case is? I think that might be a relic left over as the info seems duplicated in `Client` which is probably the better place to have it as that's where its used (in `getAndClearAudioLevel`).

Would that be ok if I added an accessor there?

**Comment by hgroenenboom** [comment]
I'm the LevelMeasure for a level visualizer

**Comment by drowaudio** [comment]
https://github.com/Tracktion/tracktion_engine/commit/89129f692d7818efda54a1df7f3cb31cea98927a

**Comment by hgroenenboom** [comment]
Thank you!
