### ISSUE TITLE
Document gets corrupted (leading to crash on open) when a plugin macro was automated by another macro that had an automation track on a track that got deleted, then save

### ISSUE THREAD

**Issue by alzwded** [Tracktion/tracktion_engine#18]
Hey, I'm on Waveform Version 9.3.2 (Built: 21 August 2018) (64-bit) and I've stumbled over an annoying crash. A couple of crashes, actually.

I started off with a bunch of tracks that all had BioTek 2 on them. I don't think the particular plugin is relevant. One of them (Track 7 I think) had a macro parameter that controlled one of the biotek parameters. Track 6 also had a macro parameter that controlled one of the biotek parameters, but also the macro on track 7. Track 6 had an automation track for its macro (the one which controlled a parameter in the biotek on track 6, but also the macro parameter on the biotek from track 7). I then duplicated Track 6 (which shifted track7 to track 8). This is where it gets funny.

I was doing some cleanup, and when deleting track 6, it would crash. I then disabled audio input and output, and that let me delete it. This shifted track 8 back to track 7. I saved.

At this point, trying to open the edit insta-crashed. The tail end of the log was:

```
1 May 2020 18:11:47  Attempting to load VST: C:\Program Files\Steinberg\VstPlugins\BioTek 2 (64 bit).dll
1 May 2020 18:11:47  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:48  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:48  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:48  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:48  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:48  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:48  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:48  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:49  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:49  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:49  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:49  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:49  Creating VST instance: BioTek 2 (64 bit)
1 May 2020 18:11:49  Initialising VST: BioTek 2 (64 bit) (2.0.9.0)
1 May 2020 18:11:50  Crash Location: tracktion_automatableparameter.cpp:tracktion_engine::AutomationCurveSource::updateInterpolatedPoints:169
1 May 2020 18:11:50  Maintenance took: 46 ms
1 May 2020 18:11:51  Crash report created: C:\Users\septi\AppData\Roaming\Tracktion\Waveform\Temporary\Crash Logs\Waveform 9.3.2 Crash Log 2020-05-01(12).dmp
1 May 2020 18:11:51  Crashed
1 May 2020 18:11:51  

1 May 2020 18:11:51  Thread 0:
1 May 2020 18:11:51    0: tracktion_automatableparameter.cpp:tracktion_engine::AutomationCurveSource::updateInterpolatedPoints:169
1 May 2020 18:11:51    1: tracktion_asyncfunctionutils.h:tracktion_engine::MessageThreadCallback::handleAsyncUpdate:178
1 May 2020 18:11:51  Thread 1:
1 May 2020 18:11:51    0: tracktion_edit.cpp:tracktion_engine::Edit::initialise:553
1 May 2020 18:11:51    1: tracktion_edit.cpp:tracktion_engine::Edit::loadFromFile:532
1 May 2020 18:11:51    2: tracktion_edit.cpp:tracktion_engine::Edit::Edit:391
```

That got me really angry. Anyway, thankfully you have a log file and methods that have reasonable names. I opened up the edit in notepad and removed the assignment from track 7 

```diff
    <FILTER type="vst" uid="54534232" filename="C:\Program Files\Steinberg\VstPlugins\BioTek 2 (64 bit).dll"
            name="BioTek 2 (64 bit)" manufacturer="Tracktion" windowLocked="1"
            id="0/32971af" enabled="1" windowX="95" windowY="55" programNum="0"
            state=">>snip<<"
            base64:layout=">>snip<<"
            base64:parameters="9.3PCL2.....3O">
      <MACROPARAMETERS mediaId="117363/12c9114">
        <MACROPARAMETER mediaId="117363/23f3b3a" name="Macro 1" value="1.0"/>
        <MODIFIERASSIGNMENTS>
-          <MACRO source="117363/30a876d" paramID="117363/23f3b3a" value="1.0"/>
        </MODIFIERASSIGNMENTS>
      </MACROPARAMETERS>
```

That got me back up and running.

Anyway, I can reproduce it with just volume&pan. Unfortunately, [I could only record a crappy video](https://www.youtube.com/watch?v=6ZQ5cjLk2ZM&feature=youtu.be) where the context menus aren't shown, but I do have this simplified edit.

[asd Edit 3.tracktionedit.txt](https://github.com/Tracktion/tracktion_engine/files/4565046/asd.Edit.3.tracktionedit.txt)

[Waveform9Log.crash.txt](https://github.com/Tracktion/tracktion_engine/files/4565098/Waveform9Log.crash.txt)

In the case of asd.Edit.3, the line that needs to be edited out is 

```diff
  <TRACK mediaId="8c4a6/1596a18" midiVProp="0.28125" midiVOffset="0.359375"
         colour="ffffaa00">
    <MACROPARAMETERS mediaId="8c4a6/96b6c1"/>
    <MODIFIERS/>
    <OUTPUTDEVICES>
      <DEVICE name="(default audio output)"/>
    </OUTPUTDEVICES>
    <FILTER type="volume" id="0/395f5b0" enabled="1" volume="0.25081819295883178711"
            base64:parameters="11.18Fa00VY.Ljo87C">
      <MACROPARAMETERS mediaId="8c4a6/fff578">
        <MACROPARAMETER mediaId="8c4a6/2ccf400" name="Macro 1" value="1.0"/>
        <MODIFIERASSIGNMENTS>
-          <MACRO source="8c4a6/14558c4" paramID="8c4a6/2ccf400" value="1.0"/>
        </MODIFIERASSIGNMENTS>
      </MACROPARAMETERS>
      <MODIFIERASSIGNMENTS>
        <MACRO source="8c4a6/2ccf400" paramID="volume" value="-0.98000001907348632813"/>
      </MODIFIERASSIGNMENTS>
      <FACEPLATE width="8" height="4" autoSize="1"/>
    </FILTER>
    <FILTER type="level" id="0/a15a80" enabled="1">
      <MACROPARAMETERS mediaId="8c4a6/35d44c5"/>
    </FILTER>
  </TRACK>
```

I don't know if you've fixed it in 10 or 11 since I haven't upgraded in a while, but I felt a need to share my crash-related frustration. If you haven't already fix it, well, please do, I hate it when programs corrupt their own documents.

Cheers

**Comment by drowaudio** [comment]
I seem to remember fixing this in W10 a while ago so it should also be fixed in Tracktion Engine.
If you can get a copy of Waveform Free and test to report back that would be very helpful.

**Comment by alzwded** [comment]
Ok, I'll try it

**Comment by alzwded** [comment]
Okay, I got Waveform 11 Free installed. I can open the edits that used to crash in 9 without modification. Apparently macro parameters are a "pro" feature so I couldn't stress test it to see what happens if I run through all those macro assignments.

**Comment by alzwded** [comment]
Closing, it seems sorted out.
