### ISSUE TITLE
tracktion_AbletonLink.cpp fails to compile on Android

### ISSUE THREAD

**Issue by awood314** [Tracktion/tracktion_engine#19]
in `tracktion_AbletonLink.cpp`, `ensureJavaEnvironmentAttachedToThread()` calls `attachAndroidJNI()`, which has been removed from `juce_android_JNIHelpers` since juce/5.4.3

**Comment by drowaudio** [comment]
I've not got an Andorid device to test on at the moment. Is there are replacement call or does it just need to be removed?

**Comment by awood314** [comment]
its hard to tell from the [commit](https://github.com/juce-framework/JUCE/commit/008b7a9ab2960f265c6ca305edfba29859a4548a), but from what I can tell it can just be removed. Seems to compile and run fine on android when I tried it locally, but I'm not using the ableton link feature.

**Comment by awood314** [comment]
ah, I neglected to notice the comment referring to this forum post: https://forum.juce.com/t/breaking-changes-in-juce-s-low-level-android-code/30338

**Comment by drowaudio** [comment]
So it can just be removed?

**Comment by awood314** [comment]
looks like it

**Comment by drowaudio** [comment]
Ok, should be fixed now: https://github.com/Tracktion/tracktion_engine/commit/17e7a525437b9569fc586e738757bbf60f587a9e
