### ISSUE TITLE
Behavior of overlapping Clips

### ISSUE THREAD

**Issue by wtholliday** [Tracktion/tracktion_engine#2]
As I understand it a Track contains a list of Clips.

What is the behavior of Clips which overlap in time? For audio clips, does it mix the audio together? What about MIDI clips?

thanks!

**Comment by drowaudio** [comment]
By default the contents of both will be sent to the Track's mix bus.
For audio, you can use the auto-crossfade option to fade between clips though.
MIDI will just send the contents of both.
Hope that helps.

**Comment by wtholliday** [comment]
Thanks!
