### ISSUE TITLE
[Bug]: Build of tracktion examples failing on Linux

### ISSUE THREAD

**Issue by SavingCaustic** [Tracktion/tracktion_engine#204]
### Detailed steps on how to reproduce the bug

Trying to compile Tracktion examples on Linux (Ubuntu) gives build-errors at 74%.

### What is the expected behaviour?

Successful build

### Operating systems

Linux

### What versions of the operating systems?

cmake version 3.22.1
28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC

### Architectures

x86_64

### Stacktrace

```shell
74%] Linking CXX shared module EngineInPluginDemo_artefacts/Release/LV2/EngineInPluginDemo.lv2/libEngineInPluginDemo.so
make[2]: *** [CMakeFiles/EngineInPluginDemo_LV2.dir/build.make:234: EngineInPluginDemo_artefacts/Release/LV2/EngineInPluginDemo.lv2/libEngineInPluginDemo.so] Segmenteringsfel << Segmentation Error
make[2]: *** Tar bort filen ”EngineInPluginDemo_artefacts/Release/LV2/EngineInPluginDemo.lv2/libEngineInPluginDemo.so”
make[1]: *** [CMakeFiles/Makefile2:289: CMakeFiles/EngineInPluginDemo_LV2.dir/all] Fel 2
make: *** [Makefile:136: all] Fel 2
```

### Testing on the `develop` branch

I have not tested against the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by drowaudio** [comment]
Can I ask how much RAM you have? And swap space?

**Comment by SavingCaustic** [comment]
Sure, currently 8GB and no swap. Will fix and post update. Thanks!

**Comment by drowaudio** [comment]
I just wonder if the linker is running out of memory...

**Comment by SavingCaustic** [comment]
No sorry, no luck with added swap. Memory not an issue. 

How to reproduce:
`cd tests
./generate_examples
then:
Building TestRunner works but not EngineInPluginDemo. SegFault as described.

(Total noob in Tracktion, so above with a pinch of salt)

**Comment by drowaudio** [comment]
It building in our CI. What version of gcc do you have installed?

**Comment by SavingCaustic** [comment]
Man, it's old..
gcc --v  => 11.4.0 
c++ --v => 11.4.0

**Comment by drowaudio** [comment]
I'm not sure what happening but our CI is passing on Ubuntu with gcc 11.4.0:

![image](https://github.com/Tracktion/tracktion_engine/assets/1065708/36330476-7e9e-40b4-b458-fcfd2551b673)
