### ISSUE TITLE
all links at the bottom of this page are invalid

### ISSUE THREAD

**Issue by datgame** [Tracktion/tracktion_engine#221]
### Detailed steps on how to reproduce the bug

see [https://github.com/Tracktion/tracktion_engine](https://github.com/Tracktion/tracktion_engine)

### What is the expected behaviour?

x

### Operating systems

Other

### What versions of the operating systems?

x

### Architectures

Other

### Plug-in formats (if applicable)

Standalone

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by drowaudio** [comment]
Thanks!
