### ISSUE TITLE
[Bug]: Failed to clone 'modules/juce'

### ISSUE THREAD

**Issue by JelleBakker** [Tracktion/tracktion_engine#225]
### Detailed steps on how to reproduce the bug

Run `git clone --recurse-submodules https://github.com/Tracktion/tracktion_engine.git`

### What is the expected behaviour?

It clones the repo

### Unit test to reproduce the error?

```bash
Not relevant
```

### Operating systems

macOS

### What versions of the operating systems?

macOS Sonoma 14.5

### Architectures

ARM

### Stacktrace

```shell
Cloning into 'tracktion_engine'...
remote: Enumerating objects: 1075880, done.
remote: Counting objects: 100% (67836/67836), done.
remote: Compressing objects: 100% (1321/1321), done.
remote: Total 1075880 (delta 66686), reused 67591 (delta 66467), pack-reused 1008044
Receiving objects: 100% (1075880/1075880), 1.18 GiB | 15.16 MiB/s, done.
Resolving deltas: 100% (1061219/1061219), done.
Submodule 'modules/juce' (git@github.com:juce-framework/JUCE.git) registered for path 'modules/juce'
Cloning into '/Users/jelle/Documents/Developer/tracktion_engine/modules/juce'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:juce-framework/JUCE.git' into submodule path '/Users/jelle/Documents/Developer/tracktion_engine/modules/juce' failed
Failed to clone 'modules/juce'. Retry scheduled
Cloning into '/Users/jelle/Documents/Developer/tracktion_engine/modules/juce'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:juce-framework/JUCE.git' into submodule path '/Users/jelle/Documents/Developer/tracktion_engine/modules/juce' failed
Failed to clone 'modules/juce' a second time, aborting
```

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by drowaudio** [comment]
This looks like you don't have an SSH key setup for GitHub?

**Comment by JelleBakker** [comment]
Possibly, I've not had this issue with Tracktion Engine (or other repo's) before.

What's the reason the submodules URL in .gitsubmodules file has changed from `https://github.com/WeAreROLI/JUCE.git` to `git@github.com:juce-framework/JUCE.git` in the commit below?
https://github.com/Tracktion/tracktion_engine/commit/0b976cfac8bbfe21a352871fa494935b6ad66b77#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584

**Comment by drowaudio** [comment]
It was because we have a new Action that pulls the latest juce tip and tries to build against it to check upstream compatibility. You can't do that with https submodules easily.
