### ISSUE TITLE
[Bug]: Removing last destination from input device does not reset input monitoring

### ISSUE THREAD

**Issue by JelleBakker** [Tracktion/tracktion_engine#238]
### Detailed steps on how to reproduce the bug

- Begin by assigning an input device to a track.
- Next, enable arm and input monitoring for that track.
- Then, remove the destination using `inputDevice->removeTarget`.
- Observe that input monitoring remains active.

The issue arises when the last destination is removed from an InputDeviceInstance, as createLiveInputsNode is not triggered. Upon investigation, we traced the problem to `InputDeviceInstance::updateRecordingStatus()`. This function iterates through all destinations and invokes `edit.restartPlayback();` when destinations have changed. However, if the destinations list becomes empty, even when destinationsChanged is true, this code does not execute because it is inside the for loop. We suggest that `edit.restartPlayback();` should potentially be moved outside of the for loop.

### What is the expected behaviour?

When a track is removed from an input device, input monitoring (live playback) should be disabled. This should also happen when the removal of the track results in the destination list becoming empty.

### Operating systems

macOS

### What versions of the operating systems?

macOS 15.0.1

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by drowaudio** [comment]
Is `destinationsChanged` true in this situation?

If we change the function to:
```
void InputDeviceInstance::updateRecordingStatus()
{
    bool restartPlayback = destinations.isEmpty(); // The below loop won't be called when the last destination has been removed but we need to make sure we rebuild the graph
    [...]
        // This logic rebuilds the audio graph if the monitor state changes as it's a static node-type in the graph
        if (destinationsChanged || (! wasRecording && wasLivePlayActive != isLivePlayActive))
            restartPlayback = true;
    [...]
    }

    if (restartPlayback)
        edit.restartPlayback();
    [...]
```
Does that resolve the issue?

**Comment by JelleBakker** [comment]
@drowaudio works here, thanks!

**Comment by drowaudio** [comment]
Fixed here: https://github.com/Tracktion/tracktion_engine/commit/f43c09af233b9d744f2254268bfebe7b22ff22aa
