### ISSUE TITLE
VS2019 Warnings

### ISSUE THREAD

**Issue by jrlanglois** [Tracktion/tracktion_engine#29]
Had to screenshot two sets because different ones popped up when trying fix a couple warnings locally.

![image](https://user-images.githubusercontent.com/1908886/100033242-d0d08380-2dc7-11eb-853d-c11b1527cdd7.png)

![image](https://user-images.githubusercontent.com/1908886/100033500-58b68d80-2dc8-11eb-9c21-bbe779314cbe.png)

**Comment by drowaudio** [comment]
Can I check what project you're compiling here and what SDK/toolset?
For some reason I'm not seeing these..

**Comment by jrlanglois** [comment]
Strange..

It looks like you have to `Use Latest` as the latest C++ language standard in the Projucer, which sets the VS project to the preview version of the latest. I believe this was the default when I created the JUCE project.

![image](https://user-images.githubusercontent.com/1908886/100101443-3a847800-2e30-11eb-84eb-1d353e3fb19a.png)

I can simply force it back to C++17 for the time being?

**Comment by drowaudio** [comment]
Yeah I think so. We've not started thinking about C++20 support yet but I'll add it to my list.
