### ISSUE TITLE
Commercial license doc

### ISSUE THREAD

**Issue by joshka** [Tracktion/tracktion_engine#3]
I like the idea of a commercial license for personal use of this library as the GPL limits can be otherwise problematic. Is there a more detailed license doc available than https://www.tracktion.com/develop/tracktion-engine?

**Comment by drowaudio** [comment]
We're just preparing this at the moment and it should be available on that page in December.

**Comment by teotigraphix** [comment]
So, what does the "Under $50k" on that page mean?

> commercial license for persona

What does that exactly mean?

**Comment by drowaudio** [comment]
This will be fully clarified in the licence we release in December but if you hover over the "i" on the information page you'll see

> An annual revenue capacity or funds raised capacity of $50k per fiscal year exists for Personal customers.

Hope that helps.

**Comment by teotigraphix** [comment]
Thanks @drowaudio, yeah that is basically what I understood.

**Comment by MIDIculous** [comment]
Does the license include the entire daw including Effects or just the sequencer portion?

**Comment by drowaudio** [comment]
This is now up and can be found from the main README: https://github.com/Tracktion/tracktion_engine/blob/master/README.md
