### ISSUE TITLE
Unimplemented functions in WarpTimeManager

### ISSUE THREAD

**Issue by jrlanglois** [Tracktion/tracktion_engine#43]
Please see `setWarpEndMarkerEnabled` and `setEndMarkersLimited`.

**Comment by drowaudio** [comment]
Do you actually need these functions? It looks to me like they're set automatically depending on which constructor is called.
I'd be more inclined to just remove them and the `areEndMarkersLimited` function as that's not used by us either...

**Comment by jrlanglois** [comment]
Nope, not needed. I simply spotted them as such and am pointing it out here

**Comment by drowaudio** [comment]
Ok, fixed here: https://github.com/Tracktion/tracktion_engine/commit/e19ca19d23db1382066598457323c4844e9bc10c
