### ISSUE TITLE
licensing clarification: GPLv3 only or GPLv3 or later?

### ISSUE THREAD

**Issue by Be-ing** [Tracktion/tracktion_engine#47]
LICENSING.md does not state whether this library is licensed GPLv3 *only* or GPLv3 *or later*. With Mixxx we now have a [crisis](https://github.com/mixxxdj/mixxx/pull/3476) with a GPLv2 only dependency which the author is refusing to relicense so we can't use GPLv3 dependencies together with it. We're going to rewrite that so we can use modern dependencies, but it would be horrible to end up in a similar situation in the future if there is ever a GPLv4. So before considering using Traktion Engine, can you clarify what the license is?

**Comment by drowaudio** [comment]
Thanks for highlighting this issue. We're discussing it and hopefully can modify the licence to fit your use case soon.

**Comment by Be-ing** [comment]
Great, thank you. To clarify, I'm not asking you to downgrade to GPLv2 or later, only to add an "or later" to the existing GPLv3 license.

**Comment by drowaudio** [comment]
Ok, I've added this here: https://github.com/Tracktion/tracktion_engine/commit/21e65ef9f81b31b117a6aac11b8c403f79c40a8a
It's on the tracktion_graph branch but that is our current working branch and will make its way across to develop/master as it stabalises.

**Comment by Be-ing** [comment]
Great, thanks for taking care of this!
