### ISSUE TITLE
.referTo() don't work on tracktion_graph branch

### ISSUE THREAD

**Issue by BaraMGB** [Tracktion/tracktion_engine#48]
Hi, I'm using this, to connect my Volume knob to the volume. It works very nice on develop branch but don't work on tracktion_graph branch. 

`m_volumeKnob.getValueObject().referTo(audioTrack->getVolumePlugin()->volume.getPropertyAsValue());`

The develop branch seems to be outdated since juce changed:
`virtual void audioProcessorChanged (AudioProcessor* processor) = 0;`
to:
`virtual void audioProcessorChanged (AudioProcessor* processor, const ChangeDetails& details) = 0;`

**Comment by drowaudio** [comment]
Yes, we've realised that you can't use the CachedValues directly if they're controlling AutomatableParameters as they don't get written back to the state correctly. We're in the process of deciding whether we can catch this misuse with assertions or if we need to make them private instead.

You should always interact with `AutomatableParameter`s using `setParameter`/`getCurrentValue` value.

**Comment by drowaudio** [comment]
Have a look the the new [DistortionEffectDemo](https://github.com/Tracktion/tracktion_engine/blob/master/examples/DistortionEffectDemo.h) and the `ParameterValueSource` for a good way to do this.
