### ISSUE TITLE
generate_examples fails to build on Mac OS Catalina

### ISSUE THREAD

**Issue by mxactvtd** [Tracktion/tracktion_engine#51]
a bunch of errors related to apparently depractaed juce code like:

```
      expanded from macro 'forEachXmlChildElement'
    for (auto* (childElementVariableName) : ((parentXmlElement).macroBasedForLoop(), (parentXmlElem...
```

From the JUCE docs it says about this function: 

> New code should avoid this macro, and instead use getChildIterator directly.

Hope this is enough info, to me it is unclear what version of juce, traction is built for, and I think Juce just updated, should I downgrade JUCE, wait for an update of tracktion, or somehow fix the code?

Sorry I am still very new to this.

Thanks a ton!

**Comment by drowaudio** [comment]
I think this is all fixed on the tracktion_engine branch so use that for the time being until it is merged in to develop/master.
Cheers.
