### ISSUE TITLE
tracktion_ExternalPlugin.h:85:90: No member named 'deprecatedUid' in 'juce::PluginDescription'

### ISSUE THREAD

**Issue by akivab** [Tracktion/tracktion_engine#53]
```
    juce::String getPluginUID() const           { return juce::String::toHexString (desc.deprecatedUid); }
```

Found when opening project after running ./generate_examples

**Comment by drowaudio** [comment]
Can I ask what branch you are using?
It looks like JUCE hasn't been updated on the branch you're using.

**Comment by akivab** [comment]
Just pulled latest master

**Comment by akivab** [comment]
Running `git submodule update` seems to fix -- might have been an issue with using tracktion_graph before

**Comment by drowaudio** [comment]
I think you need to do a `git submodule update` to make sure the JUCE submodule is at the correct commit.

**Comment by akivab** [comment]
Yes that seems to be it! thanks
