### ISSUE TITLE
can we have any command line example?

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#55]
can we have any command line example?

**Comment by drowaudio** [comment]
Hi there, the benchmarks and test examples are run as command line apps. You can see how we do that here: https://github.com/Tracktion/tracktion_engine/blob/master/examples/tracktion_graph_PerformanceTests.h

They use a lot of the utility classes in this file to open an Engine, Edit and run it: https://github.com/Tracktion/tracktion_engine/blob/master/examples/common/tracktion_graph_Dev.h

Hope that helps.

**Comment by imiskolee** [comment]
I write a play & record demo on OSX. it's working. can hear track #1, track #2, 
and successful recording wave file into disk checked the wave file, it's also can be work after double click it.

the problem is I can not hear the track #3 when 
```c
    edit->getTransport().setCurrentPosition(0.0);
    edit->getTransport().play(false);
```

Can  I know what's things I am missing?

```c
void demo1() {
    ju::File editFile("./demo1.proj");
    te::Engine engine("Demo1");
    std::unique_ptr<te::Edit> edit = te::createEmptyEdit(engine,editFile);
    edit->ensureNumberOfAudioTracks(4);
    ju::Array<te::AudioTrack*> tracks = te::getAudioTracks(*edit);
    edit->playInStopEnabled = true;
    
    {
        printf("Handle Track #1 \n");
        te::AudioTrack* track = tracks[0];
        auto f= ju::File("/Users/miskolee/develop/src/noiselabs/noise-engine/platform/examples/samples/mono-music-clip.wav");
        te::AudioFile audioFile(engine,f);
        te::ClipPosition postion;
        postion.offset = 0;
        postion.time.start = 0.0;
        postion.time.end = audioFile.getLength();
        track->insertWaveClip("Demo1",f,postion,false);
    }
    
    {
        printf("Handle Track #2 \n");
        te::AudioTrack* track = tracks[1];
        auto f= ju::File("/Users/miskolee/develop/src/noiselabs/noise-engine/platform/examples/samples/sin440-22050.wav");
        te::AudioFile audioFile(engine,f);
        te::ClipPosition postion;
        postion.offset = 1.0;
        postion.time.start = 0.0;
        postion.time.end = audioFile.getLength();
        track->insertWaveClip("Demo2",f,postion,false);
    }

    te::InputDeviceInstance *ins;
    {
        printf("Handle Track #3 \n");

        auto &dm = engine.getDeviceManager();
        for (int i = 0; i < dm.getNumWaveInDevices(); i++)
            if (auto wip = dm.getWaveInDevice (i))
                wip->setStereoPair (false);

        for (int i = 0; i < dm.getNumWaveInDevices(); i++)
        {
            if (auto wip = dm.getWaveInDevice (i))
            {
                wip->setEndToEnd (true);
               wip->setEnabled (true);
            }
        }

        edit->getTransport().ensureContextAllocated();
        printf("Handle Track #3 \n");


        for (auto instance : edit->getAllInputDevices())
        {
            if (instance->getInputDevice().getDeviceType() == te::InputDevice::waveDevice)
            {
                if (auto t = tracks[2])
                {
                    instance->setTargetTrack (*t, 0, false);
                    instance->setRecordingEnabled (*t, true);
                    if(instance->isOnTargetTrack(*t,0)) {
                        printf("Start live mode...\n");
                        instance->getInputDevice().flipEndToEnd();
                        ins = instance;
                    }
                }
            }
        }
        
    }
    edit->restartPlayback();
    edit->getTransport().record(false);
    te::EditFileOperations(*edit).save(true,true,false);

    sleep(4);


    edit->getTransport().stopIfRecording();

    printf("Start Playing\n");


    edit->getTransport().stop(false,false);
    ins->setRecordingEnabled (*tracks[2], false);
    te::EditFileOperations(*edit).save(true,true,false);
    edit->getTransport().setCurrentPosition(0.0);
    edit->getTransport().play(false);
    sleep(30);
    //track1 = play audio
    //track2 = recording
    //track3 = synth
}

```

**Comment by imiskolee** [comment]
find the issue, we need call API `ensureContextAllocated(true)` always when updated any AudioTrackSetting

**Comment by drowaudio** [comment]
Ok.
I can't guarantee that this kind of inline program will work though. Tracktion Engine requires an unblocked message thread to update itself (which is probably why you're having to call `ensureContextAllocated(true)` manually) and I can imagine lots of things not working in this situation.

If you want a CLI app, you really need to follow the examples by starting a JUCE application launching the Edit and then running timers to space events out rather than sleeping the main thread. It's just not designed to do that for anything more than simple tasks like rendering or archiving I'm afraid.

**Comment by imiskolee** [comment]
> Ok.
> I can't guarantee that this kind of inline program will work though. Tracktion Engine requires an unblocked message thread to update itself (which is probably why you're having to call `ensureContextAllocated(true)` manually) and I can imagine lots of things not working in this situation.
> 
> If you want a CLI app, you really need to follow the examples by starting a JUCE application launching the Edit and then running timers to space events out rather than sleeping the main thread. It's just not designed to do that for anything more than simple tasks like rendering or archiving I'm afraid.

thank you. I will learn the examples.
