### ISSUE TITLE
how can we get realtime dB value on timer

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#60]
hi:

i am building the Mixer widget now, and can not find a way to get the last dB value with a timer for update UI.

**Comment by imiskolee** [comment]
looks like it's LevelMeter Plugin and `LevelMeasurer` ?

**Comment by drowaudio** [comment]
Yes, just get the `LevelMeasurer` from the `LevelMeterPlugin` and call its `getAndClearAudioLevel` etc. methods on a timer.
