### ISSUE TITLE
how can we directly play a clip before insert track?

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#63]
hi:

I am want to preview a midi file on dragging into track, so, can we play it before insert track?

**Comment by drowaudio** [comment]
There's several ways to do this, one would be to create a new Edit to preview the file. You'd need to set it up to have the same synth etc. as the target track. Take a look at `Edit::createEditForPreviewingFile`.

The other approach would be to simply add the file to the track and play that region and just remove it if they decide not to add it.

Does that help?

**Comment by imiskolee** [comment]
@drowaudio is just 1 track in my case, so  #2 it's better for me.  thanks a lots!
