### ISSUE TITLE
how to copy track?

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#68]
hi:

already has clip cloneFrom method to copy & paste clip, but can not found track level copy&paste method. did it's existing ?

**Comment by drowaudio** [comment]
Copy and paste is more involved than simply duplicating the data as there are various itemIDs that need to be updated. You need to go via the `Clipboard` class to create a `Clipboard::Tracks` with the tracks ValueTree state objects and then paste that in to another position with `pasteInToEdit`.

Does that help?

**Comment by imiskolee** [comment]
it's work fine.
