### ISSUE TITLE
high cpu even nothing to do, can not understand why high cpu on tracktion_engine staff.

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#79]
![image](https://user-images.githubusercontent.com/4303880/139577945-79b13874-0f4a-4b0e-ab17-3728fe2e04a9.png)

**Comment by drowaudio** [comment]
You might be better off bringing these topics up in the JUCE forum under the "Tracktion Engine" topic or maybe the [GitHub Discussions](https://github.com/Tracktion/tracktion_engine/discussions) so more people see them and can share their knowledge?
___
Regarding performance, did this turn out to not be an issue for you?
The default threading model is tuned for the lowest latency with large graphs (thousands of Nodes) at the expense of some CPU. If you have a smaller app or a mobile target, you might be better running single-threaded or with a different `ThreadPoolStratedgy`.
