### ISSUE TITLE
looks like can not apply time range for fade in / fade out now?

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#82]
hi:

i think fade in / fade out always working on clip begin or end ? can not apply a selection from user ?

**Comment by julianstorer** [comment]
Please stop opening all these issues just to ask questions! 

Github issues are for *reporting bugs*. They're not the right place to ask questions or to discuss how things work. We've got a discussion board for that here: https://github.com/Tracktion/tracktion_engine/discussions
