### ISSUE TITLE
can not understand Project & Edit?

### ISSUE THREAD

**Issue by imiskolee** [Tracktion/tracktion_engine#85]
hi:

I checked the source code, i see the project class can be impl project folder for related resources, but I don known how to add edit to a project.

**Comment by drowaudio** [comment]
You'd normally use `Project::createNewItem` or `Project::createNewEdit` to create an Edit which references a Project.

You also might be better off posting generally discussions like this on the JUCE forum with the "Tracktion Engine" tag as there will be other members of the community able to help there and we try to reserve GitHub issues for bug tracking.
