### ISSUE TITLE
Feature Request: Add an engine behavior for maxPluginsOnClip/Track

### ISSUE THREAD

**Issue by jklein24** [Tracktion/tracktion_engine#86]
We're bumping up against these limits, so would be cool to be able to configure them for our use case. Thanks!

**Comment by drowaudio** [comment]
This change should be what you need. I'll merge it to develop once it clears the CI: https://github.com/Tracktion/tracktion_engine/commit/cdd806f143784b57a37af62011dd6532b6f1dda7
