### ISSUE TITLE
PitchAndTimeDemo on iOS

### ISSUE THREAD

**Issue by noboomu** [Tracktion/tracktion_engine#9]
The demo compiles and runs fine, however when I attempt to play a loaded file I am unable to hear anything. 
The test in the settings works however. 
The waveform displayed appears truncated.
Is there a specific wav format I need to be using? 
Also, the iOS file chooser allows the selection of files from iCloud and Google Drive, do I need to do anything special with these file sources?

**Comment by drowaudio** [comment]
What format are you trying to play? It should be able to play any standard wav file. Are you testing on a device or in the simulator. It's probably a good idea to copy the file in to your app bundle for testing purposes.

If you want the tempo and key to be automatically detected however, it will need to have the ACID metadata in it.

We haven't tested this with iCloud and Google Drive as these are recent additions to the JUCE library I'm afraid.

**Comment by noboomu** [comment]
Thanks for the quick reply. I was trying with pcm_s16le and pcm_s32le on both the device and simulator. I'll add the ACID metadata and include in the bundle to see if that helps. Should the file chooser be able to detect bundled wav files or is this something I should hardcode? Thanks again.

**Comment by drowaudio** [comment]
That's something you'll need to hard code I think, probably using the `juce::File::getSpecialLocation` method to resolve the path.

**Comment by noboomu** [comment]
Not exactly elegant but I moved the documents into the GarageBand folder and am now able to load the wav files. Demo works now. Thanks!
