### ISSUE TITLE
build scripts don't work on linux

### ISSUE THREAD

**Issue by BaraMGB** [Tracktion/tracktion_engine#94]
I'm on Linux Mint 20.2 (Ubuntu 20.04)

I followed the instructions in the README.md:

clone the repo. go to tests/linux/ and run ./generate_exemples

ends in: 

`Building example: TestRunner
Re-saving file: /home/steffen/Projects/tracktion_engine/examples/projects/TestRunner/TestRunner.jucer
Error when saving: At least one of your modules has missing dependencies!
Please add the required dependencies, or run the command again with the "--fix-missing-dependencies" option.
`
try to run the coomand with the "--fixx-missing-dependencies" option end with the exact same error.

Now I tried to run: ./build_examples wich ends in:

`Compiling include_juce_audio_formats.cpp
In file included from ../../JuceLibraryCode/JuceHeader.h:29,
                 from ../../Source/Main.cpp:9:
../../../../../modules/tracktion_engine/tracktion_engine.h:38:3: error: #error "You must define JUCE_MODAL_LOOPS_PERMITTED=1 to use Tracktion Engine"
   38 |  #error "You must define JUCE_MODAL_LOOPS_PERMITTED=1 to use Tracktion Engine"
      |   ^~~~~
Compiling include_juce_audio_processors.cpp
In file included from ../../Source/../../../tracktion_graph_PerformanceTests.h:30,
                 from ../../Source/Main.cpp:10:
../../Source/../../../common/tracktion_graph_Dev.h: In member function ‘virtual void TestUIBehaviour::runTaskWithProgressBar(tracktion_engine::ThreadPoolJobWithProgress&)’:
../../Source/../../../common/tracktion_graph_Dev.h:27:51: error: ‘class juce::MessageManager’ has no member named ‘runDispatchLoopUntil’; did you mean ‘runDispatchLoop’?
   27 |              if (! MessageManager::getInstance()->runDispatchLoopUntil (10))
      |                                                   ^~~~~~~~~~~~~~~~~~~~
      |                                                   runDispatchLoop
`

**Comment by drowaudio** [comment]
Can you please use the `develop` branch and try again?
Those scripts are all CMake now so should work correctly.
Let me know if you're still having trouble then.

**Comment by BaraMGB** [comment]
Okay, this works just fine. Thank you.
